-- Add updated_at column to system_settings to track when polling was last changed
ALTER TABLE public.system_settings
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Create a function to automatically update the updated_at timestamp on change
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger to avoid errors, then create it
DROP TRIGGER IF EXISTS set_system_settings_updated_at ON public.system_settings;
CREATE TRIGGER set_system_settings_updated_at
BEFORE UPDATE ON public.system_settings
FOR EACH ROW
EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- Create table to log each invocation of the evaluate-triggers cron job
CREATE TABLE IF NOT EXISTS public.evaluation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT DEFAULT 'running',
    summary TEXT,
    triggers_checked INTEGER,
    alerts_created INTEGER
);

-- Enable RLS for the new table
ALTER TABLE public.evaluation_runs ENABLE ROW LEVEL SECURITY;

-- Allow any authenticated user to read the logs. The edge function will use service_role to write.
DROP POLICY IF EXISTS "Allow authenticated users to read evaluation runs" ON public.evaluation_runs;
CREATE POLICY "Allow authenticated users to read evaluation runs" ON public.evaluation_runs FOR SELECT TO authenticated USING (true);