// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guwoanifjoowglqpoqyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1d29hbmlmam9vd2dscXBvcXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwOTAxNjcsImV4cCI6MjA3NjY2NjE2N30.HxPk2uhx8AuViGpoD9jrScTBsC3S9Kvc96JWsDFTsLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
